
@authToken = {{login.response.body.accessToken}}
###

@idLastAddedContact = {{post.response.body._id}}

### LOGIN / Get Local/JWT  token
# @name login
POST http://localhost:3030/authentication
Content-Type: application/json

{
  "strategy": "local",
  "email": "admin@example.com",
  "password": "admin"
}

###
GET http://localhost:3030/contacts/
Content-Type: application/json
Authorization: {{authToken}}
###
# @name post
POST http://localhost:3030/contacts
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": {
    "first": "Jake",
    "last": "Bauer"
  },
  "email": "jake@bfi.mail",
  "phone": "+12345679"
}

###

PATCH http://localhost:3030/contacts/{{idLastAddedContact}}
Content-Type: application/json
Authorization: {{authToken}}

{
     "email": "jack.russel@gmail.com"
}

###
// jostain syystä palauttaa virheen ettei löydä, mutta kannassa näkyy deletoituna
DELETE http://localhost:3030/contacts/{{idLastAddedContact}}
Authorization: {{authToken}}

