// 
@authToken = {{login.response.body.accessToken}}
###
@idLastAddedUser = {{post.response.body._id}}
 
### LOGIN / Get Local/JWT  token
# @name login
POST http://localhost:3030/authentication
Content-Type: application/json

{
  "strategy": "local",
  "email": "admin@example.com",
  "password": "admin"
}

###
GET http://localhost:3030/users 
Authorization: {{authToken}}


### 
GET http://localhost:3030/contacts
Authorization: {{authToken}}


###
POST http://localhost:3030/users 
Content-Type: application/json
Authorization: {{authToken}}

{
    "email": "admin1234@example.com",
    "password": "admin1234"
}

###
# @name post
POST http://localhost:3030/users 
Content-Type: application/json
Authorization: {{authToken}}

{
     "email": "user8@example.com",
    "password": "user8"
}

###
DELETE http://localhost:3030/users/{{idLastAddedUser}}
Authorization: {{authToken}}