// luotava ensin tuo joku/admin käyttäjä ja sitten login jälkeen kopsata tuo token

GET http://localhost:3030/users 
Authorization: {{authToken}}


### 
GET http://localhost:3030/contacts
Authorization: {{authToken}}


###
POST http://localhost:3030/users 
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin"
}

### LOGIN / Get JWT token
POST http://localhost:3030/authentication
Content-Type: application/json

{
  "strategy": "local",
  "email": "admin@example.com",
  "password": "admin"
}

// jostain syystä ei RESPONSE ikkunasta saa kopioitua, pitää POSTMANista kopsata
// MIKSI EI TARVI BEARER sanaa edessä ?
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJpYXQiOjE1OTU4NDMxODksImV4cCI6MTU5NTkyOTU4OSwiYXVkIjoiaHR0cHM6Ly95b3VyZG9tYWluLmNvbSIsImlzcyI6ImZlYXRoZXJzIiwic3ViIjoiM3ZxWEU5b25pVmhtVDhOUyIsImp0aSI6ImNhMGE4MzQ0LTk0YjctNDI2ZC05MjBmLWQ3YmUzNzc0YTM0NyJ9.2dD8EnNh5rzoJQ0vijPngGY2M12i6R9y5KZiZhs_aGU

### 
POST http://localhost:3030/users 
Content-Type: application/json
Authorization: {{authToken}}

{
     "email": "user2@example.com",
    "password": "user2"
}